name: Java CI with Gradle

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Make Gradle Wrapper Executable
      run: chmod +x gradlew

    - name: Build and Run Gradle Tests
      run: ./gradlew build

    - name: Upload Gradle Bundle Artifact
      uses: actions/upload-artifact@v6
      with:
        name: gradle-build-output
        path: build/
        retention-days: 1

  test-HRDPS:
    runs-on: ubuntu-latest
    needs: build
    env:
      TZ: 'America/Toronto'

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Download Build Artifacts
      uses: actions/download-artifact@v6
      with:
        name: gradle-build-output
        path: build/

    - name: Install System Dependencies (Xvfb & OpenGL)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libpango1.0-dev libglu1-mesa-dev

    - name: Test HRDPS
      timeout-minutes: 3
      run: xvfb-run --auto-servernum ./gradlew run --args="$(tr '\n' ' ' < test/grid/HRDPS.txt)"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: Output-files
        path: output/
        retention-days: 7

