name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install Xvfb (Virtual Display)
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxrender1 libxtst6 libxi6

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle Wrapper Executable
      run: chmod +x gradlew

    - name: Build and Run Gradle Tests
      run: ./gradlew build

    - name: Test HRDPS
      timeout-minutes: 2
      run: ./gradlew run --args="$(tr '\n' ' ' < test/grid/HRDPS.txt)"

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Output-files
        path: output/

