name: Scheduled Tasks

on:
  schedule:
    # Runs at 04:15 UTC every day
    - cron: '15 4 * * *'
  workflow_dispatch: # Allows you to also trigger this job manually via the GitHub UI

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v6

    - name: Make Gradle Wrapper Executable
      run: chmod +x gradlew

    - name: Build and Run Gradle Tests
      run: ./gradlew build

    - name: Upload Gradle Bundle Artifact
      uses: actions/upload-artifact@v6
      with:
        name: gradle-build-output
        path: build/
        retention-days: 1


  RDPS00Z-024-048:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Download Build Artifacts
      uses: actions/download-artifact@v7
      with:
        name: gradle-build-output
        path: build/

    - name: Test RDPS
      timeout-minutes: 10
      run: |
        xvfb-run --auto-servernum ./gradlew \
        run --args="$(tr '\n' ' ' < test/grid/RDPS.txt) \
        begin=24 end=48 step=3"

    - name: Upload Artifacts
      uses: actions/upload-artifact@v6
      with:
        name: RDPS-output
        path: output/
        retention-days: 1
